// Code generated by op-codegen - DO NOT EDIT

package onepassword

import (
	"github.com/dschaller/onepassword-sdk-go/internal"
)

// Client represents an instance of the 1Password Go SDK client.
type Client struct {
	config  internal.ClientConfig
	Secrets SecretsAPI
	Items   ItemsAPI
	Vaults  VaultsAPI
	inner internal.InnerClient
}

// Release the client.
//
// This will call the underlying release client function in the shared wasm module
// for the client as well as close the plugin instance to free up any memory
// associated with the client.
func (c *Client) Release() {
	if c.inner.ID != nil {
		c.inner.Core.ReleaseClient(c.inner.ID)
	}
}

func initAPIs(client *Client, inner internal.InnerClient) {
	client.Secrets = NewSecretsSource(inner)
	client.Items = NewItemsSource(inner)
	client.Vaults = NewVaultsSource(inner)
}
